# kubeval-ignore
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: chromefarm.superpro.io-production
spec:
  secretName: chromefarm.superpro.io-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - 'chromefarm.superpro.io'
  acme:
    config:
      - dns01:
          provider: gke-clouddns
        domains:
          - 'chromefarm.superpro.io'
