# kubeval-ignore
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: scorpion-crawler.superpro.io-production
spec:
  secretName: scorpion-crawler.superpro.io-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - 'scorpion-crawler.superpro.io'
  acme:
    config:
      - dns01:
          provider: gke-clouddns
        domains:
          - 'scorpion-crawler.superpro.io'
